### PR TITLE
Added a command for create transformer

### PR DESCRIPTION
**Pull request by fd6130**
This PR is for solving the issue from #20.

### CODE REVIEW

**Comment by samjarrett** [comment]
Does this break anything if the maker bundle is not installed?

**Comment by fd6130** [comment]
> Does this break anything if the maker bundle is not installed?

It use some of the classes such as `Str`, `Generator` and `AbstractMaker` from `maker-bundle`, so the command won't work if user don't have `maker-bundle` in their project i think.

**Comment by fd6130** [comment]
Any feedback on this one?

And another question: Should i change it to "ask for entity class name, and generate a new transformer class in  `App\Transformer\YourEntityTransformer.php` for example`, or "ask for transformer class name and generate a new transformer class" instead ?

**Comment by GPHemsley** [comment]
I think most other makers just ask for the name and don't bother trying to perform any additional logic, so that'd probably the best route here. Besides, I'm not sure there's much difference in terms of the output? I suppose you could get fancy with it, but that might not meet everyone's needs.

**Comment by fd6130** [comment]
> I think most other makers just ask for the name and don't bother trying to perform any additional logic, so that'd probably the best route here. Besides, I'm not sure there's much difference in terms of the output? I suppose you could get fancy with it, but that might not meet everyone's needs.

Hmm so i will stick to the "ask for transformer class name and generate a new transformer class", user will fill in whatever they need in that new class. Will update this later.

**Comment by GPHemsley** [comment]
Circling back to this...

@fd6130: It looks like there's an opportunity here to prompt for includes like make:entity prompts for properties: then you can populate availableIncludes and defaultIncludes, plus create the corresponding includeX method.

Thoughts on also doing a make:fractal:serializer? (Seems to be distinct from the Symfony serializer.)

**Comment by fd6130** [comment]
> Circling back to this...
> 
> @fd6130: It looks like there's an opportunity here to prompt for includes like make:entity prompts for properties: then you can populate availableIncludes and defaultIncludes, plus create the corresponding includeX method.
> 
> Thoughts on also doing a make:fractal:serializer? (Seems to be distinct from the Symfony serializer.)

Ahh almost forgot this PR, I will see what i can do with the "availableInclude" and "defaultInclude" when i have the time.

I think i will remove the prompt of asking user to enter an entity when creating transformer (because not every transformer are bound to an entity).

And also, what is the benefit of "make:fractal:serializer" ? Just create an empty fractal serializer like creating a transformer?

**Comment by GPHemsley** [comment]
> I think i will remove the prompt of asking user to enter an entity when creating transformer (because not every transformer are bound to an entity).

You could always allow a blank to bypass the prompt, thereby giving the user the option.

> And also, what is the benefit of "make:fractal:serializer" ? Just create an empty fractal serializer like creating a transformer?

Yeah, exactly. Since `League\Fractal\Serializer\SerializerAbstract` is abstract, it has some required methods that need to be implemented for a Serializer to work. Not sure if there's much in the way of options that can be customized at the command prompt level, though. In any case, upon further thought, definitely outside the scope of this PR.

**Pull request closed without merging**
